export const data = [
  {
    categoryName: "Consulting",
    categoryId: "fa_PjtanaTMghWk7Jy9Ig",
    services: [
      {
        samples: [],
        rateUSD: 250,
        rateUnit: "per hour",
        rateINR: 4000,
        specialOffers: "First 2 sessions are free of charge",
        testimonials: [],
        serviceDescription:
          "Every individual needs a coach. It's not a luxury anymore. Being a certified practitioner of NLP (Neuro-Linguistic Programming), I am offering you my time as a coach to help you through your problems. We work by understanding the problem statement to its absolute depth and then solving for the root cause, not just to make the symptoms go away.",
        serviceId: "cUxiVOeh963TtheRaCRd5",
        serviceName: "Life Coaching: Individual",
      },
      {
        rateUSD: 300,
        serviceName: "Business Consulting",
        serviceId: "oAKTj8fmzukvDdbrG2yWR",
        specialOffers: "First 2 sessions are free of charge",
        testimonials: [],
        samples: [],
        rateUnit: "per hour",
        serviceDescription:
          "You're caught in the day-to-day of your business and unable to focus on the big picture? Or all you see is the big picture? Does it seem like no matter what you do, your business isn't working out? Together, we're going to figure out how to ensure that your business survives the brutal world and go on to thrive in it!",
        rateINR: 5000,
      },
    ],
    categoryDescription: "",
  },
  {
    categoryName: "Content Writing",
    services: [
      {
        serviceId: "NxgBn2DxrEnkV3qegrJqO",
        specialOffers: "",
        rateUnit: "per word",
        testimonials: [],
        rateUSD: 1,
        samples: [],
        rateINR: 1,
        serviceDescription: "",
        serviceName: "Blog post",
      },
      {
        rateUnit: "per post",
        testimonials: [],
        serviceName: "Instagram post",
        speacialOffers: "",
        serviceId: "BPwhcQAF-yoMVdSQ_mRrq",
        serviceDescription: "",
        rateINR: 1000,
        rateUSD: 100,
        samples: [],
      },
      {
        samples: [],
        rateUnit: "per carousel",
        specialOffers: "",
        rateUSD: 150,
        serviceDescription: "",
        serviceId: "m1radIRW-bKLpJHvFBGZx",
        serviceName: "Instagram carousel",
        rateINR: 1500,
        testimonials: [],
      },
      {
        serviceDescription: "",
        rateUSD: 100,
        rateINR: 1000,
        serviceId: "0ltPjMI8aS01FIm2PcxHo",
        testimonials: [],
        specialOffers: "",
        samples: [],
        serviceName: "LinkedIn post",
        rateUnit: "per post",
      },
      {
        testimonials: [],
        rateINR: 1500,
        rateUSD: 150,
        serviceDescription: "",
        serviceId: "vVmQhlfIR2dp-6hyjtApd",
        serviceName: "LinkedIn carousel",
        rateUnit: "per carousel",
        specialOffers: "",
        samples: [],
      },
    ],
    categoryDescription:
      "Your business exists because it solves a problem that the world around you needs solving. To capture the attention of potential customers, we need to talk about these problems, in every way possible. This is where I come in",
    categoryId: "Dl0gV8SZqjE6V_3u4YyIf",
  },
  {
    categoryId: "ZHi4RNDOcxQQ2VTCzjUg0",
    categoryDescription:
      "Let's face it, we need to market our product directly at times. The attention span of people, and hence the word count allowed in ad platforms, is limited. If you want to make the most of the words you get, you've come to the right place",
    services: [
      {
        rateUSD: 150,
        specialOffers: "",
        serviceName: "Facebook Ad Copy",
        rateUnit: "per ad copy",
        samples: [],
        serviceDescription: "",
        testimonials: [],
        serviceId: "p6a0be8sjz1U416M53KUz",
        rateINR: 1500,
      },
      {
        rateUSD: 250,
        rateINR: 2500,
        rateUnit: "per ad copy",
        serviceDescription: "",
        samples: [],
        specialOffers: "",
        testimonials: [],
        serviceId: "3WG8KXpfdbVWswBLJVEqv",
        serviceName: "Google Ad Copy",
      },
    ],
    categoryName: "CopyWriting",
  },
  {
    services: [
      {
        specialOffers: "",
        serviceDescription: "",
        testimonials: [],
        rateUSD: 1500,
        samples: [],
        rateUnit: "per website",
        serviceId: "kOcvyS9sWSFfBGAgPcqtQ",
        serviceName: "Wix portfolio",
        rateINR: 15000,
      },
      {
        testimonials: [],
        rateINR: 20000,
        serviceId: "xVr-SnA7WTnkKJ0Yfveaa",
        rateUnit: "per website",
        serviceName: "Custom portfolio",
        specialOffers: "",
        serviceDescription: "",
        rateUSD: 2000,
        samples: [],
      },
      {
        specialOffers: null,
        testimonials: [],
        serviceId: "zmpHVsq6tqUTgEgDH9Z4V",
        rateINR: 25000,
        serviceName: "Wix website",
        serviceDescription: "",
        rateUnit: "per website",
        rateUSD: 2500,
        samples: [],
      },
      {
        testimonials: [],
        serviceId: "_wcC6JYkHWKAToTWZD3su",
        serviceDescription: "",
        rateUSD: 4000,
        specialOffers: null,
        samples: [],
        rateINR: 40000,
        serviceName: "Custom website",
        rateUnit: "per website",
      },
    ],
    categoryId: "7GLoXOw0xD3b_YkzR5xqE",
    categoryDescription:
      "Your business needs online presence now more than ever. Having an account on Instagram and a page on LinkedIn is great. However, your own website gives your business credibility, directs users to a one-stop shop and helps you expand your business in any direction that you want to! Who better to help you with a website than a developer?",
    categoryName: "Website Development",
  },
];
